---
language: node_js
node_js:
  - "6"

sudo: false

before_install:
  - npm install -g node_gyp
  - npm install -g marked
  - npm install libavahi-compat-libdnssd-dev

install:
  - npm install

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build_webpack
  repo: "alonski/coinpanion"
  project_name: coinpanion
  target_branch: gh-pages
  on:
    branch: master